import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dir } from "i18next";
import { languages } from "@/modules/i18n/settings";
import { LanguageSwitcher } from "@/modules/i18n/components/LanguageSwitcher";
import { useTranslation } from "@/modules/i18n";
import Link from "next/link";
import { redirect } from "next/navigation";

export async function generateStaticParams() {
  return languages.map((locale) => ({ locale }))
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string
  },
}>) {

  const { t } = await useTranslation(locale);

  // 
  if (!languages.some(locale => locale) ) redirect(`/${languages[0]}`);

  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={'min-h-screen flex flex-col items-center  ' + inter.className}>
        <header className="container flex items-center justify-between my-10">
          <h1 className="font-extrabold text-base sm:text-lg md:text-2xl  mr-auto">NEXT.JS LOCALIZED</h1>  
          <nav>
            <Link
              href={`/${locale}`}
              className="text-white text-sm"
            >
              { t('home-title') }
            </Link>
            <Link
              href={`/${locale}/about`}
              className="text-white text-sm ml-4"
            >{ t('about-title') }</Link>
          </nav>
          <LanguageSwitcher locale={locale} className=" text-white ml-8 text-sm" />
        </header>
        <main className="flex flex-col items-center p-24">
          {children}
        </main> 
        <footer className="mt-auto py-4">
          <p className="text-center text-gray-500">© {new Date().getFullYear()} Next.js Localized | { t('footer.created-by') } <a target="__blank" href="https://juannunezblasco.es" className="">@juannunezblasco</a> </p> 
        </footer> 
      </body>
    </html>
  );
}
